[features]
seeds = false
[programs.localnet]
staking = "GDmUNdVnZp4q77xz7ovjeoaCn57p9esWWF85UUCPz6Kk"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/lcances/Documents/perso/Shapz/SHAPZ-PRIVATE.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
